name: Download IPTV Guide

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码仓库
        uses: actions/checkout@v3

      - name: 下载 guide.xml
        run: curl -o epg.xml https://raw.githubusercontent.com/BurningC4/Chinese-IPTV/master/guide.xml

      - name: 下载 TV-IPV4.m3u
        run: curl -o iptv.m3u https://raw.githubusercontent.com/BurningC4/Chinese-IPTV/master/TV-IPV4.m3u

      - name: 检查文件是否发生变化
        id: check_changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add epg.xml iptv.m3u
          git diff --quiet --staged || echo "::set-output name=changed::true"

      - name: 提交并推送更改
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git commit -m "Update IPTV guide and playlist"
          git push
